name: edna
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  # Core scientific stack
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab

  # Bioinformatics tools
  - biopython
  - seqkit       # This will install correctly on Linux
  - blast        # For converting database files

  # Deep learning
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly

  # Large dataset handling
  - dask
  - pip

  # pip dependencies
  - pip:
      - transformers